context("Helper functions")
test_that("aNewHope works", expect_equal(length(aNewHope()),3))
test_that("theEmpireStrikesBack works", expect_equal(length(theEmpireStrikesBack()),3))
test_that("returnOfTheJedi works", expect_equal(length(returnOfTheJedi()),3))
test_that("people works", expect_equal(length(people()),3))
test_that("places works", expect_equal(length(places()),3))